from __future__ import annotations

import hashlib
from pathlib import Path

from .io_utils import canonical_json, read_json, sha256_file, sha256_text, unique_by
from .prompts import ERROR_KINDS, build_error_rows, calibration_prompt, packet_content_hash
from .registry import load_question_set


CALIBRATION_SCHEMA = "kcb-open-memory-labels-v1"
PACKET_SCHEMA = "kcb-open-tool-error-packet-v1"


def stable_sample(rows: list[dict], count: int, seed: int) -> list[dict]:
    if count < 1 or count > len(rows):
        raise ValueError(f"invalid sample size {count} for {len(rows)} rows")
    ordered = sorted(
        rows,
        key=lambda row: hashlib.sha256(
            f"{seed}|{row['source_episode_id']}".encode("utf-8")
        ).hexdigest(),
    )
    selected = ordered[:count]
    return sorted(selected, key=lambda row: (row["instance_id"], row["hop_idx"], row["source_episode_id"]))


def calibration_tasks(root: Path, *, count: int | None = None, seed: int = 20260704) -> list[dict]:
    questions = load_question_set(root)["questions"]
    if count is not None:
        questions = stable_sample(questions, count, seed)
    return [
        {
            "task_id": question["source_episode_id"],
            "source_episode_id": question["source_episode_id"],
            "question": question["question"],
            "gold_answer": question["gold_answer"],
            "prompt": calibration_prompt(question),
        }
        for question in questions
    ]


def load_memory_labels(path: Path, profile_id: str) -> tuple[dict, dict[str, dict]]:
    document = read_json(path)
    if document.get("schema_version") != CALIBRATION_SCHEMA:
        raise ValueError("unsupported memory-label schema")
    if document.get("profile_id") != profile_id:
        raise ValueError("memory labels were generated by a different execution profile")
    scored = document.get("scored")
    if not isinstance(scored, list):
        raise ValueError("memory labels have no scored records")
    return document, unique_by(scored, "source_episode_id")


def select_balanced_review(questions: list[dict], labels: dict[str, dict], count: int, seed: int) -> list[dict]:
    if count < 2:
        raise ValueError("review count must be at least 2")
    correct: list[dict] = []
    incorrect: list[dict] = []
    for question in questions:
        label = labels[question["source_episode_id"]]
        gold = str(question["gold_answer"]).strip().lower()
        text = str(question["question"]).strip().lower()
        if label["memory_absent"] or gold in text:
            continue
        (correct if label["memory_correct"] is True else incorrect).append(question)
    n_correct = count // 2
    n_incorrect = count - n_correct
    if len(correct) < n_correct or len(incorrect) < n_incorrect:
        raise ValueError(
            f"cannot build balanced review: correct={len(correct)}, incorrect={len(incorrect)}, "
            f"required={n_correct}/{n_incorrect}"
        )
    chosen = stable_sample(correct, n_correct, seed) + stable_sample(incorrect, n_incorrect, seed + 1)
    return sorted(chosen, key=lambda row: (row["instance_id"], row["hop_idx"], row["source_episode_id"]))


def build_error_packet(
    root: Path,
    profile: dict,
    memory_labels_path: Path,
    *,
    mode: str,
    count: int = 12,
    seed: int = 20260704,
) -> dict:
    question_doc = load_question_set(root)
    questions = question_doc["questions"]
    label_doc, labels = load_memory_labels(memory_labels_path, profile["profile_id"])
    question_ids = {row["source_episode_id"] for row in questions}
    if mode in ("full", "smoke") and set(labels) != question_ids:
        raise ValueError("official error packets require complete 280-question memory labels")
    if mode in ("full", "smoke") and label_doc.get("official") is not True:
        raise ValueError("smoke/full packets require official calibration labels")
    if mode == "smoke":
        questions = select_balanced_review(questions, labels, count, seed)
    elif mode == "pilot":
        questions = [row for row in questions if row["source_episode_id"] in labels]
        questions.sort(key=lambda row: (row["instance_id"], row["hop_idx"], row["source_episode_id"]))
    elif mode != "full":
        raise ValueError("mode must be pilot, smoke, or full")
    rows = build_error_rows(questions, labels)
    rows.sort(
        key=lambda row: hashlib.sha256(f"{seed}|error-task|{row['task_id']}".encode("utf-8")).hexdigest()
    )
    packet = {
        "schema_version": PACKET_SCHEMA,
        "mode": mode,
        "profile_id": profile["profile_id"],
        "model_key": profile["model_key"],
        "backend": profile["backend"],
        "real_tool_calls": False,
        "question_set_sha256": sha256_file(root / "data" / "questions_280.json"),
        "memory_labels_path": str(memory_labels_path.resolve()),
        "memory_labels_sha256": sha256_file(memory_labels_path),
        "question_count": len(questions),
        "variant_count_per_question": len(ERROR_KINDS),
        "task_count": len(rows),
        "memory_counts": {
            "correct": sum(labels[row["source_episode_id"]]["memory_correct"] is True for row in questions),
            "incorrect": sum(labels[row["source_episode_id"]]["memory_correct"] is False for row in questions),
            "absent": sum(labels[row["source_episode_id"]]["memory_absent"] for row in questions),
        },
        "error_kinds": list(ERROR_KINDS),
        "rows": rows,
    }
    packet["packet_content_sha256"] = packet_content_hash(rows)
    validate_error_packet(packet, profile)
    return packet


def validate_error_packet(packet: dict, profile: dict) -> dict:
    if packet.get("schema_version") != PACKET_SCHEMA:
        raise ValueError("unsupported packet schema")
    if packet.get("profile_id") != profile["profile_id"]:
        raise ValueError("packet/profile mismatch")
    if packet.get("real_tool_calls") is not False:
        raise ValueError("packet must declare real_tool_calls=false")
    rows = packet.get("rows")
    if not isinstance(rows, list) or not rows:
        raise ValueError("packet has no rows")
    unique_by(rows, "task_id")
    grouped: dict[str, set[str]] = {}
    for row in rows:
        grouped.setdefault(row["source_episode_id"], set()).add(row["error_kind"])
    if any(kinds != set(ERROR_KINDS) for kinds in grouped.values()):
        raise ValueError("packet contains incomplete or invalid error triplets")
    if packet.get("question_count") != len(grouped) or packet.get("task_count") != len(rows):
        raise ValueError("packet counts are inconsistent")
    if packet.get("packet_content_sha256") != packet_content_hash(rows):
        raise ValueError("packet content hash mismatch")
    return {
        "questions": len(grouped),
        "tasks": len(rows),
        "error_kinds": list(ERROR_KINDS),
        "packet_content_sha256": packet["packet_content_sha256"],
    }
